# This is an autogenerated file. Do not modify!

package Alpaca::Field::Any;

use Moose;
use Types::Standard qw(:all);
BEGIN { extends 'Alpaca::Field' };



__PACKAGE__->meta->make_immutable;
no Moose;

1;
